# Copyright (C) 2022, RTE (http://www.rte-france.com)
# Copyright (C) 2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

# This Ansible playbook configures libvirt to work with Ceph.

---
- name: Configure libvirt
  hosts: hypervisors:&cluster_machines
  become: true
  vars:
    rbd_pool_name: "{{ libvirt_rbd_pool | default('rbd') }}"
    pool_name: "{{ libvirt_pool_name | default('ceph') }}"
  roles:
    - configure_libvirt
